### ISSUE TITLE
Unknown flag --continue-last

### ISSUE THREAD

**Issue by bitcoinmeetups** [charmbracelet/mods#109]
Hello,

I'm Mr. Cherry, a very friendly guy.

mods --continue-last "hello" outputs error:

Unknown flag --continue-last

Environment: raspberry pi 4, debian

**Comment by catgoose** [comment]
Same with `--title` `--continue` and `--list` as referenced in features.md:

https://github.com/charmbracelet/mods/blob/main/features.md

**Comment by johnd0e** [comment]
Perhaps that is because you are trying outdated binaries from Releases.
Ask maintainers to make release from fresh sources.

**Comment by catgoose** [comment]
> Perhaps that is because you are trying outdated binaries from Releases. Ask maintainers to make release from fresh sources.

Thanks, I'm using the latest version now by:

cloning repo
`go install`

**Comment by toby** [comment]
This is now live in [v1.0.0](https://github.com/charmbracelet/mods/releases/tag/v1.0.0).
