### ISSUE TITLE
-C and -c arguments don't read stdin

### ISSUE THREAD

**Issue by rkintzi** [charmbracelet/mods#132]
I consider this a missing feature.

Here is what I got instead:
```
$ echo hello world | mods -C

   ERROR  You must specify a prompt.

  Missing prompt
```

**Comment by HoffsMH** [comment]
It does you just ALSO have to provide a prompt via -P

For instance something like 

```
#!/bin/bash

tempfile=$(mktemp)

nvim -c "$" "$tempfile"

cat "$tempfile" | mods --continue $(date-str) -P "see attached file:"

rm "$tempfile"
```

will work. This has been my primary use case so far so would be my primary use case for this so :+1:
