### ISSUE TITLE
go installation on windows

### ISSUE THREAD

**Issue by asystat** [charmbracelet/mods#153]
I installed mods with go successfully:
`go install github.com/charmbracelet/mods@latest`

after installation, my PC crashes just by running mods on git bash.
Do you have any recommendation for installing on windows?

**Comment by caarlos0** [comment]
just did it in a windows VM here, and it works fine.

what error are you getting?

**Comment by SenZmaKi** [comment]
> I installed mods with go successfully: `go install github.com/charmbracelet/mods@latest`
> 
> after installation, my PC crashes just by running mods on git bash. Do you have any recommendation for installing on windows?

use winget 
```
winget install charmbracelet.mods
```

**Comment by caarlos0** [comment]
@SenZmaKi thanks for the comment! Yeah, winget is an option, although `go install` should work just fine as well.

Either way, since OP did't reply, and no one else reported similar issues, I'll close this.

Thanks!
