### ISSUE TITLE
You need to document Azure OpenAI carefully, especially the Alias ​​and api-key-env parts are very confusing.

### ISSUE THREAD

**Issue by Lexloff** [charmbracelet/mods#156]
As title

**Comment by Lexloff** [comment]
https://github.com/charmbracelet/mods/issues/138

**Comment by bashbunni** [comment]
I'm going to close this as it is a duplicate of #138, will look at ways we can improve the docs here. If you have any suggestions, please don't be shy to follow up on the other issue! :) Thanks for letting us know how the docs can be improved
