### ISSUE TITLE
Saved Conversations feedback messages are getting in the way.

### ISSUE THREAD

**Issue by MadBomber** [charmbracelet/mods#161]
Is there a way to turn off the saved conversations feedback messages?

BTW where are those conversations saved?  I'd like to go in a delete a bunch.

**Comment by MadBomber** [comment]
Here is how I delete the entire conversation history ...

```bash
mods -l | awk '{print $1}' | xargs -I {} mods -d {}
```

**Comment by caarlos0** [comment]
If I understand correctly, you don't want mods to show the "Conversation saved" message, correct?

If so, you ignore stderr, e.g.:

```sh
$ mods tell me a joke 2>/dev/null

  Why don't scientists trust atoms?

  Because they make up everything!
```

Regarding deleting conversations, in the next version it'll be possible to run `mods --delete-older-than=[duration]`.

Hope that helps!
