### ISSUE TITLE
freezes on raspberry pi os

### ISSUE THREAD

**Issue by umontano** [charmbracelet/mods#163]
It often freezes when executing a prompt in raspberry pi 3 B+, debian 11.
The whole system freezes, so no error message.

**Comment by umontano** [comment]
The whole system freezes, so no error message.

**Comment by caarlos0** [comment]
could not repro this on my rpi

```
pi@pi4:~ $ uname -a
Linux pi4 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

will close for now, but if this is still happening, please provide more details: installation method, `uname -a` output, and the command that caused the issue


Thanks!
