### ISSUE TITLE
Support Local Llamafile binary/server?

### ISSUE THREAD

**Issue by anoldguy** [charmbracelet/mods#168]
This is the worst kind of issue. A feature request based on a newly released related tool. I'm sorry. 🫣

With the recent release of [llamafile](https://github.com/Mozilla-Ocho/llamafile) it'd be really cool to be able to run this completely locally without sending data up to OpenAI.

Edit: This seems similar in spirit to #162. 👍

**Comment by garyblankenship** [comment]
In `mod --settings`, you can edit the values to point to a locally hosted OpenAI compatible API like that provided by LMStudio or llamafile.

example:
```
apis:
  openai:
    base-url: http://localhost:1234/v1
    api-key: abc123

```

I'm not sure yet, but it might be possible to add llamafile or lmstudio, etc.. as additional apis in the settings.
