### ISSUE TITLE
Suggestion: Introduce --delete-older-than flag to remove older conversations

### ISSUE THREAD

**Issue by sylv-io** [charmbracelet/mods#169]
btw, thanks for this great tool. I use it a lot and it has improved many of my workflows.

After some time I collected a lot of conversations and was looking for an easy way to delete older ones. Currently the only way to do this is to use a script to delete each conversation explicitly.

How about we introduce the `--delete-older-than' flag, analogous to the use of [nix-collect-garbage](https://nixos.org/manual/nix/stable/command-ref/nix-collect-garbage#options), where we can automatically delete any conversation older than the period we choose.

e.g.
```
# delete all conversations older than 8 hours
mods --delete-older-than 8h
# delete all conversations older than 2 weeks
mods --delete-older-than 2w
# delete all conversations older than 1 year
mods --delete-older-than 1y
```

In my opinion, we should not rely on [time.ParseDuration](https://pkg.go.dev/time#ParseDuration) to define the duration because it does not define the suffix for weeks, months, or years. Instead, we should write our own parser and not expect it to be too precise in terms of month length or leap years.
IMHO we should not support minutes and use `m` for months instead, but I'm open to any suggestions on the period format.

Like my last [suggestion](#149), I'm happy to work on this feature, but it probably won't be as easy as the last time. :wink: 

Any thoughts?

**Comment by caarlos0** [comment]
see #185

**Comment by sylv-io** [comment]
awesome! thanks
