### ISSUE TITLE
Feature Request: add text area mode to enter a new input

### ISSUE THREAD

**Issue by jessicatarra** [charmbracelet/mods#180]
Hello mods team :)

I've wanted for quite some time to use a CLI tool to interact with my preferred LLM models, best way to incorporate AI to your work, so thank you so much for this project.

My issue is the following: I use mods quite frequently but occasionally face a couple of issues when inserting extensive inputs. Let's say, for instance, I'd like to include some code as part of an input. I'd typically wrap it within triple backticks, but I'd like a streamlined way to go back and forth, enabling me to modify the final input effortlessly. Therefore, would it be possible to incorporate a  `--text-area` mode flag? This would open a text area bubble component, providing a more comfortable way for me to type my prompt and then pass the value as the prompt input. 

In fact, I've actually forked this repository and have been working on this feature for my own use. However, it would be fantastic if it could be incorporated into the official codebase, potentially benefitting others who might find it helpful.

Example ⬇️ 
<img width="716" alt="Screenshot 2024-01-01 at 10 52 53" src="https://github.com/charmbracelet/mods/assets/65210800/8c030322-a51e-4898-ab19-2e7addcb4bb9">

**Comment by caarlos0** [comment]
hey, this is released on latest, if you run `mods` with no args it'll open a textarea in which you can write the prompt!

I hope this does what you need, will close, but reopen if not :) 

Cheers
