### ISSUE TITLE
repl mode

### ISSUE THREAD

**Issue by johnd0e** [charmbracelet/mods#204]
Do not exit after output. Ask next prompt instead.

This mode could be activated with some keyboard shortcut.
E.g. Shift+Enter (instead of Enter)

**Comment by jpillora** [comment]
+1 

I'd like to use `mods` as a replacement for the chatgpt interface, I assumed `mods` would be a back-and-forth chat - was surprising that it exits after one response

**Comment by caarlos0** [comment]
duplicated of #197
