### ISSUE TITLE
ram usage?

### ISSUE THREAD

**Issue by sedlund** [charmbracelet/mods#211]
im running mods on nix, and I notice after about the 3rd -C continuation of the same conversation mods us using like 1GB of ram on invocation.  In one really long convo it OOM'd my VM to swap death (6GB ram VM with 9GB of zram) where it killed it

```
Jan 30 13:46:00 fsa kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Jan 30 13:46:00 fsa kernel: [3717276]  1000 3717276  3768783  1073135 26411008  2184467             0 mods
Jan 30 13:46:00 fsa kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=gitea-runner-codeberg.service,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=mods,pid=3717276,uid=1000
Jan 30 13:46:00 fsa kernel: Out of memory: Killed process 3717276 (mods) total-vm:15075132kB, anon-rss:4292540kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:25792kB oom_score_adj:0
Jan 30 13:46:00 fsa systemd-journald[538]: Under memory pressure, flushing caches.
Jan 30 13:44:30 fsa systemd-resolved[845]: Under memory pressure, flushing caches.
Jan 30 13:44:31 fsa systemd-resolved[845]: Flushed all caches.
```

is anyone else having memory problems with it?

also - the character scroller progress indicator thing is cute and all, but i dont know that I need that much data to go over the ssh wire on a cellular connection maybe put a delay in there?

> mods version 1.1.0

_Originally posted by @sedlund in https://github.com/charmbracelet/mods/discussions/209_

**Comment by caarlos0** [comment]
I could somewhat repro it here, made mods use ~1gb of ram... nothing like 15gb, but def looks like something we should improve.

I'll take a closer look soon, thanks for reporting 🙏

**Comment by remkade** [comment]
I'm having the same issue. I've had `mods` eat over 64gb of ram if the response takes a long time to generate. It seems like every 10 seconds or so mods will use all 24 cores for about a second and allocate another several gigs of ram. Eventually if the response takes a long time it will crash the system. Once the first text is streamed the RAM usage stabilizes at whatever the current peak is.

I'm using mods on my desktop to test LLMs running on a separate single board computer. Its not unusual for a response to take 120 seconds or more to start streaming if I'm processing a lot of tokens.

**Comment by caarlos0** [comment]
can you try #249? 

run the prompt that gives you the high mem usage, but pass the `--memprofile` flag.

you should be able to stop it at some point in time and still have the profiles written to the current dir

I tried to repro this with all sorts of scheananigans, but couldn't... so maybe this PR helps with this and future problems 🙏

**Comment by remkade** [comment]
Alright, I ran this for a good 30 minutes or so with `--memprofile`. However, the bad news is that it never wrote out a profile because it never hit an error. It ran forever until I had to `kill -9` it since the system was starting to fail.

Here's the command that will trigger it for me everytime:
```bash
pdftotext ./tiny-llm-reviews/seattle-tax-instructions.pdf - | ./mods --memprofile -f 'Summarize this document with bullet points for each step'
```
I'm on Gentoo Linux with `go version go1.22.2 linux/amd64`.

The model (`qwen 1.5 0.5b`) is running on a lichee pi4a across the network. On a larger body of text like this is not unusual for it to take about 10 minutes to send a response. I noticed after about 2 minutes it had hit about 25% of the total ram, at at 10 it had eaten everything.

[seattle-tax-instructions.pdf](https://github.com/charmbracelet/mods/files/15142642/seattle-tax-instructions.pdf)

**Comment by remkade** [comment]
Also, it looks like the model finished its work and closed connection but `mods` never left the generating state.

Here's the raw text that `pdftotext` will output. I'm not sure if its important to have it in the pipe, but just in case here's the text. 

[seattle-tax-instructions.txt](https://github.com/charmbracelet/mods/files/15142667/seattle-tax-instructions.txt)

**Comment by caarlos0** [comment]
FWIW you should be able to ctrl+c it in the middle and it should generate the profile files

**Comment by caarlos0** [comment]
btw, to clarify, it eats up ram even before it gets the first bytes from the response? is that correct? 🤔

**Comment by remkade** [comment]
Yeah it never starts steaming the response. By the time it used all the ram
nothing was responding to the control c. I'll try again and cancel before
it hits that point.

**Comment by caarlos0** [comment]
I will also try to artificially repro this here by adding a sleep on the client! 

thanks for the input 🙏

**Comment by remkade** [comment]
Here's the memprofile after running it for a little while. I control-c'ed it and then eventually had to `kill` it. It took about 1 full minute to respond. It seems like its stuck in some sort loop and won't respond to user input.

[memprofiles.zip](https://github.com/charmbracelet/mods/files/15150446/memprofiles.zip)

**Comment by caarlos0** [comment]
okay, I _think_ I found it: https://github.com/charmbracelet/bubbletea/pull/993

**Comment by caarlos0** [comment]
was actually a pretty sneaky one, https://github.com/charmbracelet/mods/pull/252

should be good on main!

thanks for the patience and for all the input 💜

**Comment by sedlund** [comment]
seems to work well, and lower cpu usage. 👍

had to update my config with the default roles and disable checks in my nix overlay for the new network based check

```nix
mods-main = let
  pname = "mods";
  version = "1.2.2+main";
  src = pkgs.fetchFromGitHub {
    owner = "charmbracelet";
    repo = "mods";
    rev = "90fd02f4667fa791766d022401cefadc58efd95f";
    hash = "sha256-sT98KDbTno8g0S6Jy/5BL+CfMsZ6395/6iSXA2TCE2Y=";
  };
in
  pkgs.mods.override {
    buildGoModule = args:
      pkgs.buildGoModule {
        inherit pname version src;
        vendorHash = "sha256-VAmHxlL7muaFkW353GSVetCBXSnAnboP3QJGoU5jwak=";

        # There is a test that uses network breaking which fails in sandbox
        doCheck = false;
      }
      // args;
};
```

**Comment by caarlos0** [comment]
oh, right, let me improve that one

**Comment by caarlos0** [comment]
I could run a testserver for http, but https would be tricky... probably your solution is OK enough for now
