### ISSUE TITLE
Gemini Support

### ISSUE THREAD

**Issue by dezren39** [charmbracelet/mods#216]
Hey!

This morning I picked up the new Gemini chatbot from Google, it has an API key and so I wondered if it could be hooked up to mods?

- https://makersuite.google.com/app/prompts/new_freeform
- https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini

maybe i'll get inspired to try adding this myself sometime, until then I open this

**Comment by dezren39** [comment]
duplicates #176

**Comment by johnd0e** [comment]
@dezren39 
Google Gemini can be used with `mods` this way: https://github.com/PublicAffairs/openai-gemini
