### ISSUE TITLE
Should be able to edit settings if the config is broken

### ISSUE THREAD

**Issue by chand1012** [charmbracelet/mods#220]
A corrupted configuration is preventing me from editing my configuration file.
<img width="637" alt="image" src="https://github.com/charmbracelet/mods/assets/3521582/463bf779-93a4-4a88-a1a7-97173412c66b">
You should be able to run `mods --settings` even if the config file is broken so you can fix it. I was able to fix this error by going to the config file directly.

**Comment by weiqiangt** [comment]
I've also met this problem, anyone know where is real configuration located?

**Comment by weiqiangt** [comment]
The raw config is located at `'~/Library/Application Support/mods/mods.yml'`.
