### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by HaleTom** [charmbracelet/mods#232]
I would love to use the system prompt feature that's not yet included in any release.

Would you consider dropping one? (Please feel free to point me at the release management doco if this question is already answered somewhere)

Cheers for a great tool!

**Comment by bashbunni** [comment]
Hey, thanks for the nudge. It's definitely on our to do list to have more consistent releases. Will bring this up with the team and aim to get one out asap :)

**Comment by bashbunni** [comment]
@HaleTom Just released a new version. Thanks again :)
https://github.com/charmbracelet/mods/releases/tag/v1.2.2
