### ISSUE TITLE
Claude Support

### ISSUE THREAD

**Issue by garyblankenship** [charmbracelet/mods#233]
We could add support for Claude maybe from AnthropicAI. https://docs.anthropic.com/claude/reference/messages_post

**Comment by SynapticSage** [comment]
this thread might be relevant

https://github.com/charmbracelet/mods/issues/176

code on discord shows the path

**Comment by HaleTom** [comment]
@SynapticSage 

> discord thread: [discord.com/channels/1032368467246075914/1199064780376391861/1199064780376391861](https://discord.com/channels/1032368467246075914/1199064780376391861/1199064780376391861)

I can't access this... does it work for you an incognito browser?

**Comment by HaleTom** [comment]
This may help?

https://github.com/jtsang4/claude-to-chatgpt

**Comment by johnd0e** [comment]
Related PR: #243

**Comment by cloudbridgeuy** [comment]
PR #243 has a working version of Anthropic support for Claude.

![image](https://github.com/charmbracelet/mods/assets/127410436/e3e89b7f-817b-4485-b0a9-d8d4533a8236)

**Comment by cloudbridgeuy** [comment]
These changes have been added on #256. You can try them out by building from source:

```bash
# Clone the project and run:
go build -ldflags "-s -w" .
```

**Comment by caarlos0** [comment]
I think this is fixed, right?

closing!

**Comment by caarlos0** [comment]
and thanks everyone <3
