### ISSUE TITLE
Scoop instructions don't work

### ISSUE THREAD

**Issue by RuiNtD** [charmbracelet/mods#234]
The instructions in the README to install Mods on Windows with Scoop don't work, since the `bucket add` command is missing a bucket name, a required argument:
```
~> scoop bucket add https://github.com/charmbracelet/scoop-bucket.git
Unknown bucket 'https://github.com/charmbracelet/scoop-bucket.git'. Try specifying <repo>.
usage: scoop bucket add <name> [<repo>]
```

A name argument needs to be added before the URL. I personally just used `charm`, but it doesn't matter too much. The bucket name is mainly used in case there's a package conflict between buckets so you can type `scoop install charm/mods`, for example.
```
~> scoop bucket add charm https://github.com/charmbracelet/scoop-bucket.git
Checking repo... OK
The charm bucket was added successfully.
```

**Comment by caarlos0** [comment]
ah, good catch, thanks!

just fixed it
