### ISSUE TITLE
Add theme support for the preset themes available in 'huh'

### ISSUE THREAD

**Issue by gwenwindflower** [charmbracelet/mods#236]
It would be very nice to have the `mods` TUI themed in Catppuccin! Feels like given the way y'alls libraries/frameworks build on each other this is likely a possibility so just wanted to voice interest 💗.

**Comment by peterldowns** [comment]
+1 for this. If possible, would love to be able to switch between the different catppuccin variants easily. I automatically switch my `bat` theme from catppuccin mocha to catppuccin latte in different terminal profiles using my `~/.zshrc`, [see here for more details](https://gist.github.com/peterldowns/35f3408fd29805c4c7a432511e73c964).

**Comment by peterldowns** [comment]
Oh nice it looks like `huh` might support exactly that, automatically :) https://github.com/charmbracelet/huh/blob/v0.4.2/theme.go#L242
