### ISSUE TITLE
Feature request: Add support for GPT4o

### ISSUE THREAD

**Issue by PylotLight** [charmbracelet/mods#267]
Is your feature request related to a problem? Please describe.
Update with GPT4o support

Describe the solution you'd like
gpt4o:
aliases: ["gpt4o"]
max-input-chars: ?

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by bradyjoslin** [comment]
PR #262 was merged to add the model to the default config template.  

You can add the model by updating your existing config, just as you see [here](https://github.com/charmbracelet/mods/commit/76688b276ee49dc0a27b4d4acb6913b37e44249b)
