### ISSUE TITLE
No Response ???

### ISSUE THREAD

**Issue by elhakimz** [charmbracelet/mods#275]
**Describe the bug**
I have tried many times, taking examples, but no response at all 

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS Windows 11 with Chocolatey and powershell
 - LocalAI 

![image](https://github.com/charmbracelet/mods/assets/616176/0f691333-fe72-4703-b026-5c19ae2f6a55)

**Comment by caarlos0** [comment]
does `mods --show d87f598` shows anything?
