### ISSUE TITLE
The default model is GPT-4 , which is not available for most people

### ISSUE THREAD

**Issue by ManveerBhullar** [charmbracelet/mods#42]
So most peoples[0] first couple runs will just result in 
```
   ERROR  Unknown OpenAI API error.

  error, status code: 404, message: The model: `gpt-4` does not exist
```
even if they have their openapi key set in the env vars.

Obviously we could just do `mods -m gpt-3.5-turbo blah` each time but the number of keystrokes will kill me :(

- [0]  even ppl like me who requested access months ago to gpt-4 :(

**Comment by toby** [comment]
We can definitely do a better job messaging that and also probably fallback to `gpt-3.5-turbo` if `gpt-4` isn't available. For now you can set the `MODS_MODEL` env var to `gpt-3.5-turbo` so you don't have to type the flag every time:

https://github.com/charmbracelet/mods#model

**Comment by odysa** [comment]
Can we have subcommands to list and set default models?
Example:

List all available models
```bash
mods models
```
Set default models
```
mods use "gpt-3.5-turbo"
```

**Comment by toby** [comment]
Ok, I just pushed a fallback to `gpt-3.5-turbo` when any other model 404s. If you grab the latest release, it should work without having to set the env var. Please let us know if there are any issues!

https://github.com/charmbracelet/mods/releases/tag/v0.1.1

Also, @odysa we should definitely give people a way to list their models and probably add a config file (potentially allowing people to set that interactively). Right now it's kind of nice that you can add the prefix prompt without having to specify a sub-command, so would probably prefer to use flags instead.
