### ISSUE TITLE
Provide verbose feedback option for intermediary output

### ISSUE THREAD

**Issue by bashbunni** [charmbracelet/mods#44]
>  Is there a way to see intermediary output? It's "generating" a long time for me rn and I don't know whether everything is still going well / whether I should kill the process / how many calls it made / how much money was spent / ..
-kadrian on [Discord](https://charm.sh/chat)

**Comment by toby** [comment]
This is now live in [v1.0.0](https://github.com/charmbracelet/mods/releases/tag/v1.0.0)!
