### ISSUE TITLE
[Long-Term Goal/Question] Support for local/OSS models?

### ISSUE THREAD

**Issue by 13-05** [charmbracelet/mods#46]
Hey there! This looks like a really cool project. However, I think it would be awesome if it was extended to somehow work with OSS LLM models that run locally, like [EleutherAI's GPT-NeoX](https://github.com/eleutherai/gpt-neox) or the [GPT-J based GPT4all project](https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-chat#gpt4all-chat). Is something like this on the roadmap, or will `mods` stick with OpenAI's proprietary models? I appreciate any and all responses!

**Comment by meowgorithm** [comment]
Hi there! Yes, no ETA yet but we absolutely plan on supporting open source models.

**Comment by Stetsed** [comment]
@meowgorithm So I think that this might be easier to implement than you would think by simply using [LocalAI](https://github.com/go-skynet/LocalAI), it implements the OpenAI API spec and interfaces it with local models. So maybe it would be easy by adding a flag which let's you modify where the request is sent, no refactoring of code needed.

**Comment by Stetsed** [comment]
Please ignore my previous comments as I hadn't looked at the code base properly, you are using the go-openai library which doesn't seem to support customizing the endpoint(from what I can find). So I see this would either require an update to that project upstream, or doing something custom in this library.

**Comment by toby** [comment]
I have a PR open (#54) for LocalAI support. We'll probably do an official release tomorrow but if anyone wants to test it out (and report bugs!), you can use the `local-ai` branch.

**Comment by toby** [comment]
This is now live in v0.2.0: https://github.com/charmbracelet/mods/releases/tag/v0.2.0
