### ISSUE TITLE
[feature request] option for reading OPENAI_API_KEY from file

### ISSUE THREAD

**Issue by roeniss** [charmbracelet/mods#48]
it would be nice if I could use file like `~/.openai_secret` instead of manually adding `OPENAI_API_KEY` env everytime.

Even though I can `export OPENAI_API_KEY='xxx'` in my `~/.zshrc`, it can't be the best because I'll be not able to publicly share my dotfile anymore. Or, I can do this at least:

```
// in ~/.zshrc
export OPENAI_API_KEY=$(cat ~/.openai_secret) # and make the file individually
```

but for me, it seems verbose.

If you agree on my idea, I also want to add the option with a joy!

p.s., Other options are similar case but the token would be better to be seperated

**Comment by 13-05** [comment]
Here's a patch file I made:
```patch
diff --color '--exclude=.git' -ruN mods/mods.go mods-patch-1/mods.go
--- mods/mods.go	2023-05-21 11:36:26.027555891 -0500
+++ mods-patch-1/mods.go	2023-05-21 11:34:51.880583011 -0500
@@ -187,7 +187,16 @@
 func (m *Mods) startCompletionCmd(content string) tea.Cmd {
 	return func() tea.Msg {
 		cfg := m.Config
-		key := os.Getenv("OPENAI_API_KEY")
+    key := ""
+    if _, err := os.Stat("openai_api_key.txt"); err == nil {
+      if bytes, err := os.ReadFile("openai_api_key.txt"); err == nil {
+        key = strings.TrimRight(string(bytes), "\r\n")
+        fmt.Println(key)
+      }
+    } else {
+      key = os.Getenv("OPENAI_API_KEY")
+    }
+
 		if key == "" {
 			return modsError{
 				err:    fmt.Errorf("You can grab one at %s", m.styles.link.Render("https://platform.openai.com/account/api-keys.")),
diff --color '--exclude=.git' -ruN mods/openai_api_key.txt mods-patch-1/openai_api_key.txt
--- mods/openai_api_key.txt	1969-12-31 18:00:00.000000000 -0600
+++ mods-patch-1/openai_api_key.txt	2023-05-21 11:34:51.880583011 -0500
@@ -0,0 +1 @@
+put_your_api_key_here
```
You can apply it by following these steps:
- Save it to a file called `mods_key_from_file.patch`
- Run `git clone https://github.com/charmbracelet/mods.git`
- Now, run `patch -s -p0 < mods_key_from_file.patch` to apply it

Now that the changes are applied, build the program by going into the `mods` directory and running `go build`. Now you can run the `mods` executable in the current directory, but first you'll want to modify `openai_api_key.txt` in this directory to contain *only your api key*.

**Comment by bueti** [comment]
i don't like to store tokens in plaintext files. would be nice to read it from the os keyring (eg. with https://github.com/zalando/go-keyring). i can give it a shot an create a PR if you are interested in that.

**Comment by roeniss** [comment]
> would be nice to read it from the os keyrin

That would be better! I missed native KeyChain.

**Comment by ndom91** [comment]
We could also allow a "global" user config file like `$XDG_CONFIG_HOME/mods/mods.conf`. Those should be readable by the user only anyway (i.e. at `/home/username/.config`), and is a very common pattern, right?

**Comment by bueti** [comment]
> We could also allow a "global" user config file like `$XDG_CONFIG_HOME/mods/mods.conf`. Those should be readable by the user only anyway (i.e. at `/home/username/.config`), and is a very common pattern, right?

[xdg kinda of suggests](https://www.freedesktop.org/wiki/Specifications/secret-storage-spec/) to use the OS keyring for secrets. 
I think using the OS keyring is the most secure solution and also pretty easy to implement. it would still be possible to use an environment variable or XDG_CONFIG_HOME as a fallback.

**Comment by CovertDuck** [comment]
Ideally I would leave the password/secret management to something like `pass`:
`OPENAI_API_KEY=$(pass apis/openai) mods "tell me a nice bedtime story"`

**Comment by roeniss** [comment]
@CovertDuck Not native, i'm using this way and it's pretty cozy actually

**Comment by auwsom** [comment]
I have a workaround.. 
`echo <key> > ~/.env/openai_key && echo 'export OPENAI_API_TOKEN="$(cat ~/.env/openai_key)"' >> .bashrc && bash && echo $OPENAI_API_TOKEN`
This adds the key to a file, and creates an env var that dynamically retrieves it in a bash subshell. Using `~/.env` as a directory is a standard in line with envdir and direnv.

**Comment by toby** [comment]
> Ideally I would leave the password/secret management to something like `pass`: `OPENAI_API_KEY=$(pass apis/openai) mods "tell me a nice bedtime story"`

This is the solution we recommend as well. You can make an alias for this in your `.bashrc` (or equivalent) file too.
