### ISSUE TITLE
I think you should put up a big warning in the README and make sure people get the privacy implications.

### ISSUE THREAD

**Issue by oderwat** [charmbracelet/mods#50]
This makes it much too easy to send data to OpenAI which does not belong there. I think you should add a big warning about sending your source code and other data to OpenAI. 

I would also prefer if you abstract the LLM away, so we can use local running LLM instead. Even having the API selectable would help to set it to an 'OpenAI like API' endpoint.

**Comment by Stetsed** [comment]
@oderwat there is already an open issue about allowing for people to use local LLM's in #46.

**Comment by oderwat** [comment]
Nice, but I think we (= all the people using it) need more awareness about the privacy problems cased by using OpenAI.

**Comment by toby** [comment]
I think ultimately we can have nice on-boarding for model selection that makes it clear if it's local or remote. We'll have to get there in stages though starting with support for local models.

**Comment by oderwat** [comment]
I opened this issue because of the current state where things go to OpenAI, and some user may not really think about what happens when they use the tool and run their code through it. Having other LLM is another topic. This here is about my concern that the people just use it without considering that they are sending that stuff to a third party. Of course, they did agree to the OpenAI terms, but, I fear that plenty of people just don't understand what is going on.

I am not even sure if you know the terms you agreed to when using their API: https://senseient.com/ride-the-lightning/lawyers-using-chatgpt-have-agreed-to-indemnify-openai-in-the-event-of-a-lawsuit-alleging-harm/

**Comment by toby** [comment]
We do make it clear that we're using OpenAI and that you need to set your environment variable to use `mods` in the [install instructions](https://github.com/charmbracelet/mods#installation). I think it's up to the individual users to decide if they agree to the OpenAI terms and want to access the service programmatically by issuing a token.

**Comment by oderwat** [comment]
Yes, one can have this stance. But one could also warn it's users that they probably should think about what they pipe into it.
