### ISSUE TITLE
winget installation?

### ISSUE THREAD

**Issue by tigerinus** [charmbracelet/mods#56]
it'd be nice to be able to install mods via

```
winget install mods
```

ref: https://github.com/microsoft/winget-pkgs

**Comment by bashbunni** [comment]
Hey @tigerinus thanks for mentioning this! We use [goreleaser](https://github.com/goreleaser/goreleaser) to distribute our binaries with each release. We will be adding winget to our list of supported package managers once it is supported over there :) 

related: https://github.com/goreleaser/goreleaser/issues/2290

**Comment by caarlos0** [comment]
You should be able to `winget install mods` since the last release (v1.0.0)

https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/charmbracelet/mods
