### ISSUE TITLE
You've git your OpenAI API rate limit

### ISSUE THREAD

**Issue by SenhorBardell** [charmbracelet/mods#65]
mods version dev
module version: v0.2.0, checksum: h1:/jfv3SSTMTpS7EGICUmQ8ON6vUr9cldtdnACS9ySldA=
platform windows, powershell

ERROR  You’ve hit your OpenAI API rate limit.

error, status code: 429, message: You exceeded your current quota, please check your plan and billing details.

Just pulled it on windows and see it is reporting that I've hit my rate limit, which is not true.

I've put fresh token, `Write-Output $env:OPENAI_API_KEY` prints the token to terminal.

**Comment by SenhorBardell** [comment]
Apparently I am being dumb here.

**Comment by KingJulianS** [comment]
So does one have to pay to get anything out of the API ? how else can I use it free like the web one , but on CLI

**Comment by cmartinio** [comment]
Hi @jellyninjadev how did you manage to solve this issue?  i am having the same problem, and I have my billings already setup.: this is my error ` ERROR  You’ve hit your openai API rate limit.

  error, status code: 429, message: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.`
