### ISSUE TITLE
confused by configuration file options operation - pls help

### ISSUE THREAD

**Issue by Free-Radical** [charmbracelet/mods#67]
Hi Firstly, LOVE 🥰 mods, but am confused with mods configuration file (mods -s).
I've setup the default model etc but it isn't working as expected, seems to insert some extra blank lines in the prompt.
LocalAI is working fine. 

I want to use issue the mods cmd as following - 
`$ mods "how are you today?"`

and WANT mods cmd to -
$ mods -a localai -m ./my_local_wizardlm.bin "how are you today?"

but I cant quite set the config using `mods -s `correctly for it to happen, PLS HELP!

PS issuing `$ mods -a localai -m ./my_local_wizardlm.bin "how are you today?"` works as expected 
I know I could use a shell alias to do this but prefer not to since I plan to use mods to do more  work and need the configuration to be correct

**Comment by toby** [comment]
Thank you for the kind words! Mods uses [LocalAI](https://discord.com/channels/1032368467246075914/1115877770388570112/1116107701026557972) for local model support. If you follow that tutorial, you can then reference any model you install with `-m MODEL` (you won't need to specify `-a`).
