### ISSUE TITLE
How to fix max prompt size exceeded error?

### ISSUE THREAD

**Issue by albertsj1** [charmbracelet/mods#77]
I am feeding mods a document and asking a question, just like one of the examples in the readme.

ie. 
```bash
mods -f "my question?" < mydocument.md | glow

```

Gives me the following error:

```
   ERROR  Maximum prompt size exceeded.

  error, status code: 400, message: This model's maximum context length is 4097 tokens. However, you requested 5624
  tokens (1527 in the messages, 4097 in the completion). Please reduce the length of the messages or completion.
```

How can I fix this?  Is the only way to send a smaller document?

Thank you

**Comment by toadle** [comment]
So I also have this problem. I thought it should have been fixed by using a model with bigger context/more token window like `gpt-4` or `gpt35-32k`. 

But this **Example** make me think the model-switching does not work:

```
cat wapiti.gv | mods -m 32k "Create clusters/subgraphs for GTINs, WPINs, ASINs and Manufacturer-PIDs"

   ERROR  Maximum prompt size exceeded.

  error, status code: 400, message: This model's maximum context length is 4097 tokens. However, your messages resulted in 5278 tokens. Please reduce the length of the messages.
```

The given file `wapiti.gv` is 703KB. And 5278 Tokens should be in the range of both models. 
I don't know why this is happening.

**Comment by caarlos0** [comment]
You can tune the model's `max-input-chars` in `~/.config/mods/mods.yml`, which will 'cut' the prompt at that max length.

According to [OpenAi, 1 token ~= 4 chars in english](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them), so you can base it on that and fine tune.

That said, we also experimented with some libraries that count tokens, but they didn't work properly either... so the only option for now seems to be to make estimations...

**Comment by toadle** [comment]
@caarlos0 I think I was wondering about the concrete value mentioned above: GPT-4 should have a Token-size of 8,192 tokens. Is that error coming from OpenAI or from `mods`?

**Comment by caarlos0** [comment]
yeah, the error message "This model's maximum context length is 4097 tokens. (...)" comes from OpenAI's API

**Comment by caarlos0** [comment]
fwiw, #189 should help as well

**Comment by caarlos0** [comment]
I think the changes made on main should fix this, let me know if that's not the case.

thanks, all! :)
