### ISSUE TITLE
Tokens in ENV vars is insecure (ChatGPT agrees)

### ISSUE THREAD

**Issue by rwxrob** [charmbracelet/mods#85]
Maybe next time use the tool to avoid writing insecure code.

```sh
$ mods -f 'is it safe to store passwords and tokens in environment variables?'
```

> No, it is not safe to store passwords and tokens directly in environment variables. While environment variables provide a convenient way to store configuration data, they are not designed to securely store sensitive information such as passwords and tokens.
>
> Storing passwords and tokens in environment variables can expose them to potential security risks. Environment variables are easily accessible to any process running on the same machine, making it easier for unauthorized users or malicious programs to access this sensitive data.
>
> To enhance security, it is recommended to use secure storage mechanisms specifically designed for sensitive data, such as a dedicated password manager or a secure key vault. These tools provide additional layers of protection, including encryption and access control, to safeguard sensitive information from unauthorized access.

Please add the option to read this from a file (at least).

**Comment by userbox020** [comment]
Everybody who have basic programming background knows that bro.

**Comment by toby** [comment]
A lot of OpenAI tools are leveraging the `OPENAI_API_KEY` env var, so we need to support that. I think it's beyond the scope of the app to read the key directly from a file, but you could add an alias like `alias mods="OPENAI_API_KEY=$(cat ~/.secretkey) mods` or use something like [direnv](https://direnv.net/).

**Comment by rwxrob** [comment]
> Everybody who have basic programming background knows that bro.

What a productive comment! Here's one from me.

**Comment by rwxrob** [comment]
> A lot of OpenAI tools are leveraging the `OPENAI_API_KEY` env var, so we need to support that. I think it's beyond the scope of the app to read the key directly from a file, but you could add an alias like `alias mods="OPENAI_API_KEY=$(cat ~/.secretkey) mods` or use something like [direnv](https://direnv.net/).

You're absolutely right. I immediately just wrapped this in a `gpt` command that reads the var from a file. Sorry I opened this issue without thinking of that. Maybe someone else will see it. Love this tool.
