### ISSUE TITLE
--quiet still dumps ANSI terminal escapes

### ISSUE THREAD

**Issue by rwxrob** [charmbracelet/mods#86]
They may be invisible, but they are still a problem when using the filter command from within a Vim session, for example.

```sh
$ mods --quiet 'do you like kittens'
^[[?25l ^[[0D^[[2K^[[?25h^[[?1002l^[[?1003lAs an AI, I do not have personal preferences or          emotions, so I do not have the ability to like or dislike anything, including kittens.
```

**Comment by johnd0e** [comment]
Related issue: with redirected output there should not be ANSI escapes either.

**Comment by caarlos0** [comment]
hey, thanks for reporting this!

it seems like an issue somewhere else in our stack, opened an issue to investigate

https://github.com/charmbracelet/bubbletea/issues/797

**Comment by caarlos0** [comment]
a small clarification though: `--quiet` only stops the `generating` indicator

This is still a bug nevertheless :)
