### ISSUE TITLE
Please stop releasing "tarbombs"

### ISSUE THREAD

**Issue by rwxrob** [charmbracelet/mods#90]
Your current releases create "tarbombs" that will overwrite any file with the names of the files in your release. This is a *very* well established anti-pattern in the industry. Please create a folder (probably `mods`) instead and properly tar that folder to avoid this.

**Comment by bashbunni** [comment]
@rwxrob Thanks for mentioning this! We definitely don't want to be inconveniencing users in any way. It's fixed now across our repos. Please don't hesitate to let us know if there are other ways we can improve UX :)
