### ISSUE TITLE
Issues when redirectiong stdout

### ISSUE THREAD

**Issue by johnd0e** [charmbracelet/mods#97]
```
mods -q do you like kittens>1.md
```
1. The output expected to be redirected. And it is, but in parallel it also is typed in terminal, and then cleared on exit.
2. There are ANSI sequences in `1.md`. See also #86

```

[38;5;252m[0m[38;5;252m[0m  [38;5;252mI don't have personal feelings or emotions, so I don't have the capacity to[38;5;252m [0m[0m
[0m[38;5;252m[0m  [38;5;252mlike or dislike anything, including kittens. However, I can provide[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[0m
[0m[38;5;252m[0m  [38;5;252minformation and answer questions about kittens if you're interested[0m[38;5;252m![0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m[38;5;252m [0m
```

**Comment by caarlos0** [comment]
Hey, this one should be fixed on main!

```

❯ mods -q do you like kittens >1.md

Conversation saved: 5136cc5

❯ cat 1.md
As an artificial intelligence, I don't have feelings, so I don't have a personal liking or disliking for anything. However, I can provide information, images, and videos about kittens if that's what you're interested in!

```

Thanks for reporting it :)

**Comment by johnd0e** [comment]
@caarlos0 
Have you close this intentionally?
Is the issue resolved?

I'm unable to check because after 4d10417748d2bb63c312522c6305cf704908a3e6 I only see this:
```
  ERROR  Could not open db

  could not ping db: SQL logic error: out of memory (1)
```

**Comment by caarlos0** [comment]
@johnd0e yes, the issue should be resolved... seems like you hit some other issue.

I improved the error handling on `main`, can you try it again and paste the error?

also, if it fails, which OS/arch are you on?

thanks!

**Comment by johnd0e** [comment]
> I improved the error handling on main, can you try it again and paste the error?

Thank you. There is no error now.

**Comment by caarlos0** [comment]
ah, awesome, thank you for verifying :)
